# Generated by Django 6.0.3 on 2026-04-06 23:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Gym',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Gym name', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Detailed description of the gym')),
                ('address', models.TextField(help_text='Full address of the gym')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('price_per_session', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('price_description', models.CharField(blank=True, help_text="e.g, 'Pay per session' or 'Monthly membership'", max_length=200)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='gym_covers/')),
                ('images', models.JSONField(blank=True, default=list, help_text='List of image URLS')),
                ('submission_type', models.CharField(choices=[('gps', 'GPS Detected'), ('owner', 'Owner Submitted'), ('admin', 'Admin Added')], default='owner', max_length=10)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this gym is currently active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(help_text='User who submitted/owns this gym', on_delete=django.db.models.deletion.CASCADE, related_name='owned_gyms', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Gym',
                'verbose_name_plural': 'Gyms',
                'db_table': 'gyms',
                'ordering': ['-created_at'],
            },
        ),
    ]
