# Generated by Django 6.0.3 on 2026-04-13 18:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gyms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gym',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='gym',
            name='address',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='gym',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='gym',
            name='images',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='gym',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='gym',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='gym',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_gyms', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='gym',
            name='price_description',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='gym',
            name='submission_type',
            field=models.CharField(choices=[('owner', 'Owner Submitted'), ('admin', 'Admin Added')], default='owner', max_length=10),
        ),
    ]
